# Generated by Django 4.0 on 2021-12-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Сдам...', max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/ads/')),
                ('type', models.CharField(choices=[('house', 'дом'), ('apartments', 'апартаменты'), ('apartment', 'квартира'), ('room', 'комната')], default='квартира', max_length=12)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
